project:
  type: website

website:
  title: "Aman Pande MD"
  site-url: https://www.amanpande.quarto.pub
  navbar:
    background: primary
    search: true
    left:
      - text: "About Dr Pande"
        file: about.qmd
      - text: "Publications"
        file: papers.qmd
      - text: "Presentations"
        file: talks.qmd
      - text: "The Cleveland Clinic"
        file: index.qmd 

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

 
    
